# Generated by Django 5.1.7 on 2025-03-28 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('analyzing', 'Analyzing'), ('flagged', 'Flagged as Phishing'), ('legitimate', 'Legitimate'), ('unsure', 'Unsure')], default='new', max_length=50)),
                ('phishing_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phishing_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PhishingIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('Suspicious Link', 'Suspicious Link'), ('Spoofed Domain', 'Spoofed Domain'), ('Request for Sensitive Information', 'Request for Sensitive Information'), ('Suspicious Attachment', 'Suspicious Attachment'), ('Impersonation Attempt', 'Impersonation Attempt'), ('Urgency or Pressure', 'Urgency or Pressure'), ('Grammar Errors', 'Grammar Errors'), ('Mismatched URLs', 'Mismatched URLs')], max_length=50)),
                ('description', models.TextField()),
                ('severity', models.FloatField(default=0.5)),
                ('location', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='phishing_detection.phishingemail')),
            ],
            options={
                'ordering': ['-severity'],
            },
        ),
    ]
